### ISSUE TITLE
#3 TP2 Créer un composant menu et produit 

### ISSUE THREAD

**Issue by EmmanuelDemey** [Gillespie59/devoxx-vuejs#5]
(avec événement pour incrémenter le total du panier)

**Comment by AurelienLoyer** [comment]
On part sur une liste de produit en dur pour cette step ?
Genre : 
![image](https://cloud.githubusercontent.com/assets/3717296/23104132/53952d24-f6c8-11e6-825b-c57aebf13c20.png)

**Comment by EmmanuelDemey** [comment]
Oui oui

**Comment by EmmanuelDemey** [comment]
Oui oui

Le 19 févr. 2017 17:24, "Aurélien Loyer" <notifications@github.com> a
écrit :
